sonar.projectKey=fga-eps-mds_2026.1-MeasureSoftGram-AI
sonar.organization=fga-eps-mds-1
sonar.projectName=MeasureSoftGram-AI
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.tests=tests
sonar.language=py
sonar.python.version=3.11

sonar.exclusions=src/msgram_mcp/server.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=src/msgram_mcp/server.py
